# Generated by Django 4.0.3 on 2022-03-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
