# Generated by Django 4.0.3 on 2022-03-17 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_show', '0002_alter_ratings_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movie_show.movie'),
        ),
    ]
