# Generated by Django 4.0.3 on 2022-03-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_show', '0003_alter_ratings_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(default='/movie_show/default_poster.jpeg', max_length=500),
        ),
    ]
